### ISSUE TITLE
Please provide a proper release of this some time in the near future.

### ISSUE THREAD

**Issue by akesandgren** [OpenChemistry/avogenerators#15]
Makes it easier for HPC sites to install using various tools such as EasyBuild and Spack.

**Comment by ghutchis** [comment]
Sorry, I didn't see your post. Are HPC sites using EasyBuild and Spack for GUIs? The scripts at the moment are installed with the app / avogadrolibs.

Do you want regular releases in sync with `avogadrolibs`? One reason for separating them was that the scripts can be updated more frequently.

Why don't you post to https://discuss.avogadro.cc or here and let me know a bit more of what you want.

**Comment by akesandgren** [comment]
There are quite a bunch of HPC sites that use EasyBuild and/or Spack to install a big bunch, if not all, of the scientific software, even GUIs.

A proper release makes repeatable results doable to a higher degree then using random commits from git repos. And users do like that from time to time :-)

They don't have to be in sync if there is no good reason to.

At sites using one of the above, being able to be sure that installation of software X version Y is the same each time is a BIG win. (And actually is regardless of how software is installed)

So my suggestion is simply to make tagged versions every now and then when you have something that can be considered stable and releaseable. And make them show up as a Release in the git repo.

This won't stop users that want to use the currently latest commit in any way, but it sure helps us sysadmins ...

**Comment by ghutchis** [comment]
Sorry for the delay .. it took a while to get 1.96 together. Should be solved now.
