### ISSUE TITLE
Gaussian inputs

### ISSUE THREAD

**Issue by renzha-miun** [OpenChemistry/avogenerators#17]
I have downloaded the newest version on my MAC, and used "download plugins" to install "avogenerators". I expected to see extension for generate a Gaussian input file, but I did not find it on the menu bars. I am using a MAC BigSur (11.4). Thank you.

**Comment by ghutchis** [comment]
Apologies - I do not get notifications on issues created in this repository.

I don't know what version you downloaded - hopefully 1.95.1. Input generators are on the "Input" menu. (The newest Mac version should, in fact, already have all the input generators.)

Please post in the forum linked above if you have further problems.
