### ISSUE TITLE
Geometry

### ISSUE THREAD

**Issue by mcocdawc** [OpenChemistry/avogenerators#2]
Hello,

I tried to use your module for molpro input generation.
The options work well, but I am irritated by this line:
```
output += '$$coords:Sxyz$$\n'
```
Isn't there a function missing that converts cjson files to xyz format and inserts them there?
Or what is the intended way to specify a geometry?

**Comment by cryos** [comment]
This is done in the C++, but I was just thinking about writing some simple Python utilities to do some of this. In the original design this was always coming back to the C++ side, and that would replace these blocks according to the specification.

**Comment by mcocdawc** [comment]
So it is just a magic variable to be replaced by string substitution?

**Comment by cryos** [comment]
Yes, http://doc.openchemistry.org/avogadrolibs/api/class_avogadro_1_1_mole_queue_1_1_input_generator.html provides documentation of the context in which these were developed, it was a shortcut to move to representations that were used in a number of codes.
